version: 2.1

orbs:
  python: circleci/python@3.0.0

executors:
  default:
    docker:
      - image: cimg/python:3.13

jobs:
  test:
    executor: default
    steps:
      - checkout
      - python/dist
      - run: pip install dist/sourcestack-*.whl
      - run: pip install pytest
      - run: pytest

workflows:
  build:
    jobs:
      - test
